TRAIN:
  ENABLE: True
  DATASET: hslu
  BATCH_SIZE: 4
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 40
  AUTO_RESUME: False
DATA:
  PATH_TO_DATA_DIR: " /path/to/ssv2/annotations/"
  PATH_PREFIX: "/path/to/ssv2/frames/"
  NUM_FRAMES: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False
  REVERSE_INPUT_CHANNEL: True
  MULTI_LABEL : False
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 200, 500,800]
  LRS: [1, 0.8, 0.5,0.8]
  MAX_EPOCH: 1000
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: vit_base_patch16_224
  NUM_CLASSES: 4
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.2
TEST:
  ENABLE: False
  DATASET: hslu
  BATCH_SIZE: 3
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
